version: "3.9"

services:
  base:
    environment:
      ACCRUAL_ADDR: "localhost:8081"
      GOPHERMATH_ADDR: "localhost:8080"
      POSTGRES_DB: "market"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      DB_URI: "postgres://user:test@localhost:5432/market?sslmode=disable"
