version: "3.9"
services:
  postgres:
    container_name: martdb
    image: postgres:13.3
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD", "psql", $DATABASE_URI]
        interval: 3s
        timeout: 1s
        retries: 5
    env_file: .env
  gophermart:
    container_name: gophermart
    image: market
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: cmd/gophermart/Dockerfile
    env_file: .env


